### ISSUE TITLE
Error "collection.createIndex" at start

### ISSUE THREAD

**Issue by slonofanya** [holidayextras/jsonapi-store-mongodb#21]

**Comment by pmcnr-hx** [comment]
Hi @slonofanya. Thanks for reporting this. Can you provide a stack trace?

**Comment by slonofanya** [comment]
.idea

Unhandled rejection MongoError: index name cannot be empty
    at Function.MongoError.create (/services/resources/node_modules/mongodb-core/lib/error.js:31:11)
    at /services/resources/node_modules/mongodb/lib/db.js:946:80
    at /services/resources/node_modules/mongodb-core/lib/topologies/server.js:772:13
    at Callbacks.emit (/services/resources/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at null.messageHandler (/services/resources/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/services/resources/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
From previous event:
    at Collection.createIndex (/services/resources/node_modules/mongodb/lib/collection.js:1508:10)
    at MongoStore._createIndexesForRelationships (/services/resources/node_modules/jsonapi-store-mongodb/lib/mongoHandler.js:156:14)
    at /services/resources/node_modules/jsonapi-store-mongodb/lib/mongoHandler.js:217:10
From previous event:
    at MongoStore.initialise (/services/resources/node_modules/jsonapi-store-mongodb/lib/mongoHandler.js:214:6)
    at Object.jsonApi.define (/services/resources/node_modules/jsonapi-server/lib/jsonApi.js:61:29)
    at defineResource (/services/resources/lib/load-resources.js:11:11)
    at /services/resources/lib/load-resources.js:24:26
    at Array.forEach (native)
    at module.exports.fs.readdirSync.filter.filename.forEach (/services/resources/lib/load-resources.js:24:6)
    at App.loadResources (/services/resources/lib/initializers/app.js:36:5)
    at /services/resources/server.js:12:9
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Object.<anonymous> (/services/resources/server.js:11:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3

**Comment by slonofanya** [comment]
I've created the [Pull request](https://github.com/holidayextras/jsonapi-store-mongodb/pull/20) with fixing it

**Comment by theninj4** [comment]
Thanks for the help :+1: We'll get it reviewed, merged and published soon :)
