### ISSUE TITLE
Unable to restrict access to a resource

### ISSUE THREAD

**Issue by mahlu** [holidayextras/jsonapi-store-mongodb#27]
related to [#106](https://github.com/holidayextras/jsonapi-server/issues/106)

`const MongoStore = require("jsonapi-store-mongodb")`
...
`MongoStore.prototype = _.omit(MongoStore.prototype, ['create', 'update', 'delete'])`
`module.exports = new MongoStore(db)`

C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\lib\handlerEnforcer.js:29
    original.apply(handlers, argsIn);
            ^

TypeError: Cannot read property 'apply' of undefined
    at Object.create (C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\lib\handlerEnforcer.js:29:13)
    at async.waterfall.newResource (C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\lib\routes\create.js:46:33)
    at fn (C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:746:34)
    at C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:1213:16
    at C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:166:37
    at C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:706:43
    at C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:167:37
    at Immediate._onImmediate (C:\Users\Mahlu\desktop\aggApp\node_modules\jsonapi-server\node_modules\async\lib\async.js:1206:34)
    at processImmediate [as _immediateCallback] (timers.js:516:17)

**Comment by theninj4** [comment]
I'll fix this up on the previous PR on jsonapi-server. Sorry for the confusion :(
